**Data Acquisiton and Cleaning**

In [ ]:
# libraries
import pandas as pd

In [ ]:
# this will be the base dataset
# https://www.kaggle.com/koki25ando/scotch-whisky-dataset
from google.colab import files
import io
uploaded = files.upload()
whisky86 = pd.read_csv('whisky.csv')

Saving whisky.csv to whisky.csv

In [ ]:
# preview 
whisky86.head()

   RowID Distillery  Body  Sweetness  ...  Floral    Postcode  Latitude  Longitude
0      1  Aberfeldy     2          2  ...       2  \tPH15 2EB    286580     749680
1      2   Aberlour     3          3  ...       2  \tAB38 9PJ    326340     842570
2      3     AnCnoc     1          3  ...       2   \tAB5 5LI    352960     839320
3      4     Ardbeg     4          1  ...       0  \tPA42 7EB    141560     646220
4      5    Ardmore     2          2  ...       1  \tAB54 4NH    355350     829140

[5 rows x 17 columns]

In [ ]:
# check on rows and columns
whisky86.shape

(86, 17)

In [ ]:
# check on unique Distillery names
whisky86.Distillery.unique()

array(['Aberfeldy', 'Aberlour', 'AnCnoc', 'Ardbeg', 'Ardmore',
       'ArranIsleOf', 'Auchentoshan', 'Auchroisk', 'Aultmore', 'Balblair',
       'Balmenach', 'Belvenie', 'BenNevis', 'Benriach', 'Benrinnes',
       'Benromach', 'Bladnoch', 'BlairAthol', 'Bowmore', 'Bruichladdich',
       'Bunnahabhain', 'Caol Ila', 'Cardhu', 'Clynelish', 'Craigallechie',
       'Craigganmore', 'Dailuaine', 'Dalmore', 'Dalwhinnie', 'Deanston',
       'Dufftown', 'Edradour', 'GlenDeveronMacduff', 'GlenElgin',
       'GlenGarioch', 'GlenGrant', 'GlenKeith', 'GlenMoray', 'GlenOrd',
       'GlenScotia', 'GlenSpey', 'Glenallachie', 'Glendronach',
       'Glendullan', 'Glenfarclas', 'Glenfiddich', 'Glengoyne',
       'Glenkinchie', 'Glenlivet', 'Glenlossie', 'Glenmorangie',
       'Glenrothes', 'Glenturret', 'Highland Park', 'Inchgower',
       'Isle of Jura', 'Knochando', 'Lagavulin', 'Laphroig', 'Linkwood',
       'Loch Lomond', 'Longmorn', 'Macallan', 'Mannochmore', 'Miltonduff',
       'Mortlach', 'Oban', 'OldFettercairn', 'OldPulteney',
       'RoyalBrackla', 'RoyalLochnagar', 'Scapa', 'Speyburn', 'Speyside',
       'Springbank', 'Strathisla', 'Strathmill', 'Talisker', 'Tamdhu',
       'Tamnavulin', 'Teaninich', 'Tobermory', 'Tomatin', 'Tomintoul',
       'Tormore', 'Tullibardine'], dtype=object)

In [ ]:
# turn this into a list
v = whisky86.Distillery.unique()
v = v.tolist()
type(v)

list

In [ ]:
# count the number of unique entries
whisky86['Distillery'].nunique()

86

In [ ]:
# check out column types to see if any transformations are needed
whisky86.dtypes

RowID          int64
Distillery    object
Body           int64
Sweetness      int64
Smoky          int64
Medicinal      int64
Tobacco        int64
Honey          int64
Spicy          int64
Winey          int64
Nutty          int64
Malty          int64
Fruity         int64
Floral         int64
Postcode      object
Latitude       int64
Longitude      int64
dtype: object

In [ ]:
# delete the rowID column, dont need
del whisky86['RowID']

In [ ]:
# we'll want to clean up this one to merge
# https://www.kaggle.com/koki25ando/22000-scotch-whisky-reviews
from google.colab import files
import io
uploaded = files.upload()

Saving scotch_review.csv to scotch_review.csv

In [ ]:
# pull what we've uploaded
whisky2200 = pd.read_csv('scotch_review.csv')

In [ ]:
# preview 
whisky2200.head()

   Unnamed: 0  ...                                        description
0           1  ...  Magnificently powerful and intense. Caramels, ...
1           2  ...  What impresses me most is how this whisky evol...
2           3  ...  There have been some legendary Bowmores from t...
3           4  ...  With a name inspired by a 1926 Buster Keaton m...
4           5  ...  Captivating, enticing, and wonderfully charmin...

[5 rows x 7 columns]

In [ ]:
# check on rows and columns
whisky2200.shape

(2247, 7)

In [ ]:
# check on unique column names
whisky2200.name.unique()

array(['Johnnie Walker Blue Label, 40%',
       'Black Bowmore, 1964 vintage, 42 year old, 40.5%',
       'Bowmore 46 year old (distilled 1964), 42.9%', ...,
       'Edradour Barolo Finish, 11 year old, 57.1%',
       'Highland Park, Cask #7380, 1981 vintage, 25 year old, 55%',
       "Distillery Select 'Inchmoan' (distilled at Loch Lomond), Cask #151, 13 year old, 1992 vintage, 45%"],
      dtype=object)

In [ ]:
# count the number of unique entries
whisky2200['name'].nunique()

2223

In [ ]:
# do we need currency? 
# whisky2200.currency.unique()

# nope, delete
del whisky2200['currency']

# also delete the Unnamed: 0
del whisky2200['Unnamed: 0']

In [ ]:
# remove $ and , as needed
whisky2200['price'] = whisky2200['price'].str.replace("$","")
whisky2200['price'] = whisky2200['price'].str.replace(",","")

In [ ]:
# price is currently an object

# error: could not convert string to float: '$15,000 or $60,000/set' - clean up 
whisky2200['price'] = whisky2200['price'].str.replace('15000 or 60000/set', '15000')
whisky2200['price'] = whisky2200['price'].str.replace('60000/set', '15000')
whisky2200['price'] = whisky2200['price'].str.replace('44/liter', '44')

In [ ]:
# turn to float
whisky2200['price'] = whisky2200['price'].astype(float)

In [ ]:
# check out column types to see if any transformations are needed
whisky2200.dtypes

name             object
category         object
review.point      int64
price           float64
description      object
dtype: object

In [ ]:
# pull the % out of the name column
test = whisky2200.name.str.rsplit(',', 1, expand=True)
test.head()

                                          0       1
0                 Johnnie Walker Blue Label     40%
1  Black Bowmore, 1964 vintage, 42 year old   40.5%
2      Bowmore 46 year old (distilled 1964)   42.9%
3                   Compass Box The General   53.4%
4                        Chivas Regal Ultis     40%

In [ ]:
# add new column to the whisky2200 dataframe
whisky2200['%alc'] = test[1]

In [ ]:
# pull the words out of the name column
test2 = whisky2200.name.str.split(',', 1, expand=True)
test2.head()

                                      0                                  1
0             Johnnie Walker Blue Label                                40%
1                         Black Bowmore   1964 vintage, 42 year old, 40.5%
2  Bowmore 46 year old (distilled 1964)                              42.9%
3               Compass Box The General                              53.4%
4                    Chivas Regal Ultis                                40%

In [ ]:
# add to the whisky2200 dataset
whisky2200['Distillery'] = test2[0]

In [ ]:
# rearrange the columns for ease 
# preserve "name" just in case
whisky2200 = whisky2200[['Distillery', '%alc', 'category', 'review.point', 'price', 'description', 'name']]

In [ ]:
# have to clean the distillery column up so that we can figure out how to merge with the existing dataset
# A - B
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Aberfeldy', case=False)] = 'Aberfeldy'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Aberlour', case=False)] = 'Aberlour'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('AnCnoc', case=False)] = 'AnCnoc'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Ardbeg', case=False)] = 'Ardbeg'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Ardmore', case=False)] = 'Ardmore'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Arran', case=False)] = 'ArranIsleOf'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Auchentoshan', case=False)] = 'Auchentoshan'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Auchroisk', case=False)] = 'Auchroisk'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Aultmore', case=False)] = 'Aultmore'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Balblair', case=False)] = 'Balblair'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Balmenach', case=False)] = 'Balmenach'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Balvenie', case=False)] = 'Belvenie' # this is a typo to fix in the merged dataset
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Ben Nevis', case=False)] = 'BenNevis'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Benriach', case=False)] = 'Benriach'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Benrinnes', case=False)] = 'Benrinnes'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Benromach', case=False)] = 'Benromach'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Bladnoch', case=False)] = 'Bladnoch'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Blair Athol', case=False)] = 'BlairAthol'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Bowmore', case=False)] = 'Bowmore'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Bruichladdich', case=False)] = 'Bruichladdich'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Bunnahabhain', case=False)] = 'Bunnahabhain'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:27: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# have to clean the distillery column up so that we can figure out how to merge with the existing dataset
# C - E (no F)
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Caol Ila', case=False)] = 'Caol Ila'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Cardhu', case=False)] = 'Cardhu'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Clynelish', case=False)] = 'Clynelish'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Craigellachie', case=False)] = 'Craigallechie' # this is a type to fix in merged dataset
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Cragganmore', case=False)] = 'Craigganmore' # this is a typo to fix in merged dataset

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Dailuaine', case=False)] = 'Dailuaine'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Dalmore', case=False)] = 'Dalmore'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Dalwhinnie', case=False)] = 'Dalwhinnie'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Deanston', case=False)] = 'Deanston'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Dufftown', case=False)] = 'Dufftown'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Edradour', case=False)] = 'Edradour'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app

In [ ]:
# have to clean the distillery column up so that we can figure out how to merge with the existing dataset
# G - H
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Deveron', case=False)] = 'GlenDeveronMacduff'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Macduff', case=False)] = 'GlenDeveronMacduff' # whisky2200 has glendevronmcduff in two separate, but this is the same distillery
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Elgin', case=False)] = 'GlenElgin'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('GlenGarioch', case=False)] = 'GlenGarioch'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Grant', case=False)] = 'GlenGrant'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Keith', case=False)] = 'GlenKeith'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Moray', case=False)] = 'GlenMoray'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Ord', case=False)] = 'GlenOrd'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Scotia', case=False)] = 'GlenScotia'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glen Spey', case=False)] = 'GlenSpey'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenallachie', case=False)] = 'Glenallachie'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glendronach', case=False)] = 'Glendronach'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glendullan', case=False)] = 'Glendullan'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenfarclas', case=False)] = 'Glenfarclas'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenfiddich', case=False)] = 'Glenfiddich'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glengoyne', case=False)] = 'Glengoyne'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenkinchie', case=False)] = 'Glenkinchie'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenlivet', case=False)] = 'Glenlivet'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenlossie', case=False)] = 'Glenlossie'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenmorangie', case=False)] = 'Glenmorangie'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenrothes', case=False)] = 'Glenrothes'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Glenturret', case=False)] = 'Glenturret'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Highland Park', case=False)] = 'Highland Park'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:24: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:28: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# have to clean the distillery column up so that we can figure out how to merge with the existing dataset
# I - R
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Inchgower', case=False)] = 'Inchgower'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Isle of Jura', case=False)] = 'Isle of Jura'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Knockando', case=False)] = 'Knochando' # this is a typo to be corrected in the merged dataset
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Lagavulin', case=False)] = 'Lagavulin'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Laphroaig', case=False)] = 'Laphroig' # this is a typo to be corrected in the merged dataset

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Linkwood', case=False)] = 'Linkwood'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Loch Lomond', case=False)] = 'Loch Lomond'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Longmorn', case=False)] = 'Longmorn'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Macallan', case=False)] = 'Macallan'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Mannochmore', case=False)] = 'Mannochmore'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Miltonduff', case=False)] = 'Miltonduff'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Mortlach', case=False)] = 'Mortlach'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Oban', case=False)] = 'Oban'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Fettercairn', case=False)] = 'OldFettercairn'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Old Pulteney', case=False)] = 'OldPulteney'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Royal Brackla', case=False)] = 'RoyalBrackla'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Royal Lochnagar', case=False)] = 'RoyalLochnagar'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# have to clean the distillery column up so that we can figure out how to merge with the existing dataset
# S onward (nothing after T)
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Scapa', case=False)] = 'Scapa'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Speyburn', case=False)] = 'Speyburn'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Speyside', case=False)] = 'Speyside'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Springbank', case=False)] = 'Springbank'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Strathisla', case=False)] = 'Strathisla'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Strathmill', case=False)] = 'Strathmill'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Talisker', case=False)] = 'Talisker'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Tamdhu', case=False)] = 'Tamdhu'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Tamnavulin', case=False)] = 'Tamnavulin'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Teaninich', case=False)] = 'Teaninich'

whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Tobermory', case=False)] = 'Tobermory'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Tomatin', case=False)] = 'Tomatin'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Tomintoul', case=False)] = 'Tomintoul'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Tormore', case=False)] = 'Tormore'
whisky2200['Distillery'][whisky2200['Distillery'].str.contains('Tullibardine', case=False)] = 'Tullibardine'

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # This is added back by InteractiveShellApp.init_path()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  app.launch_new_instance()
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:19: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# Cask #9219 throwing an error for % alc
# print('single condition:',whisky2200.index[whisky2200["%alc"]=='Cask #9219'].tolist())
whisky2200.iloc[[93]]

# google search says this is 49.7%

   Distillery  ...                                            name
93   Belvenie  ...  Balvenie 1973 Vintage, 30 year old, Cask #9219

[1 rows x 7 columns]

In [ ]:
# clean up % alc column
whisky2200['%alc'] = whisky2200['%alc'].str.replace("Cask #9219","49.7%")

In [ ]:
# error - could not convert string to float: '” 46.7'
# print('single condition:',whisky2200.index[whisky2200["%alc"]=='” 46.7'].tolist())
whisky2200.iloc[[123]]

     Distillery  ...                                 name
123  Glenrothes  ...  The Glenrothes “John Ramsay,” 46.7%

[1 rows x 7 columns]

In [ ]:
whisky2200['%alc'].iloc[[123]] = '46.7%'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [ ]:
# look for additional issues with % alcohol -- Aberfeldy
# print('single condition:',whisky2200.index[whisky2200["Distillery"] == "Aberfeldy"].tolist())
whisky2200.iloc[[43, 181, 781, 984, 985, 1171, 1198, 1344, 1562, 1565, 1615, 1728, 1925]]

     Distillery  ...                                               name
43    Aberfeldy  ...           Aberfeldy 14 year old Single Cask, 58.1%
181   Aberfeldy  ...  Aberfeldy Single Cask (Cask No. 5) 16 year old...
781   Aberfeldy  ...                        Aberfeldy, 21 year old, 40%
984   Aberfeldy  ...  Cask & Thistle (distilled at Aberfeldy), 29 ye...
985   Aberfeldy  ...  That Boutique-y Whisky Company (distilled at A...
1171  Aberfeldy  ...  Gordon & MacPhail Cask Strength 1995 (distille...
1198  Aberfeldy  ...                         Aberfeldy 18 year old, 40%
1344  Aberfeldy  ...  Wemyss Malts Snuffed Candle (distilled at Aber...
1562  Aberfeldy  ...  Wemyss Malts Melon Vine 1994 (distilled at Abe...
1565  Aberfeldy  ...  Wemyss Malts Toffee Tuile (distilled at Aberfe...
1615  Aberfeldy  ...                         Aberfeldy 16 year old, 40%
1728  Aberfeldy  ...  Wemyss Malts Banquet of Fruits 1994 (distilled...
1925  Aberfeldy  ...                        Aberfeldy, 12 year old, 40%

[13 rows x 7 columns]

In [ ]:
# Aberfeldy	1974 Vintage has a non % value in %alc
# goolge search says this is 40%
# https://www.thewhiskyexchange.com/p/5257/aberfeldy-1974-connoisseurs-choice
whisky2200['%alc'].iloc[[984]] = '40.0%'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [ ]:
# look for issues with % alcohol: Glenlossie
# print('Glenlossie:',whisky2200.index[whisky2200["Distillery"] == "Glenlossie"].tolist())
whisky2200.iloc[[1956, 1957]]

      Distillery  ...                                               name
1956  Glenlossie  ...  Gordon & MacPhail (distilled at Glenlossie), 2...
1957  Glenlossie  ...  Murray McDavid (distilled at Glenlossie) 1975,...

[2 rows x 7 columns]

In [ ]:
# Gordon & MacPhail (distilled at Glenlossie), 27 year old, 1978 vintage, cask #1815
# google search says this is 46%
# https://whiskyauctioneer.com/lot/5032131/glenlossie-1978-gordon-and-macphail
whisky2200['%alc'].iloc[[1956]] = '46.0%'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [ ]:
# look for additional issues with % alcohol -- Bowmore
# print('Bowmore:',whisky2200.index[whisky2200["Distillery"] == "Bowmore"].tolist())
whisky2200.iloc[[1, 2, 6, 7, 20, 47, 48, 49, 96, 97, 189, 302, 303, 304, 305, 352, 419, 420, 421, 422, 423, 424, 608, 609, 610, 611, 613, 717, 806, 807, 935, 1014, 1015, 1016, 1017, 1225, 1226, 1227, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1642, 1643, 1644, 1802, 1803, 1901, 1934, 2025, 2026, 2077, 2099, 2100, 2139, 2200]]

     Distillery  ...                                               name
1       Bowmore  ...    Black Bowmore, 1964 vintage, 42 year old, 40.5%
2       Bowmore  ...        Bowmore 46 year old (distilled 1964), 42.9%
6       Bowmore  ...                 Gold Bowmore, 1964 vintage, 42.4%
7       Bowmore  ...                        Bowmore, 40 year old, 44.8%
20      Bowmore  ...        Bowmore 50 year old (distilled 1961), 40.7%
47      Bowmore  ...  Signatory (distilled at Bowmore), 35 year old,...
48      Bowmore  ...    White Bowmore, 1964 vintage, 43 year old, 42.8%
49      Bowmore  ...                    Bowmore 1966 50 year old, 41.5%
96      Bowmore  ...          Bowmore, 16 year old, 1989 vintage, 51.8%
97      Bowmore  ...  The Whisky Exchange Masterpieces Range (distil...
189     Bowmore  ...          Bowmore Oloroso Sherry Cask, 1964 Vintage
302     Bowmore  ...                          Bowmore, 25 year old, 43%
303     Bowmore  ...                          Bowmore, 18 year old, 43%
304     Bowmore  ...  Duncan Taylor (distilled at Bowmore), Cask #85...
305     Bowmore  ...  Bowmore Vault Edition Atlantic Sea Salt (First...
352     Bowmore  ...                          Bowmore, 18 year old, 43%
419     Bowmore  ...            Bowmore, 34 year old, 1971 vintage, 51%
420     Bowmore  ...                  Bowmore Darkest, 15 year old, 43%
421     Bowmore  ...  A. D. Rattray (distilled at Bowmore), 18 year ...
422     Bowmore  ...  Adelphi (distilled at Bowmore) 12 year old 200...
423     Bowmore  ...           Bowmore Devil’s Casks 10 year old, 56.9%
424     Bowmore  ...                 Bowmore Laimrig 15 year old, 53.7%
608     Bowmore  ...             Bowmore Fino Cask, 1964 Vintage, 49.4%
609     Bowmore  ...                                Bowmore Voyage, 56%
610     Bowmore  ...                               Bowmore Claret (56%)
611     Bowmore  ...  Blackadder (distilled at Bowmore), 27 years ol...
613     Bowmore  ...  Wemyss Malts The Rockpool (distilled at Bowmor...
717     Bowmore  ...  Wemyss Malts Cacao Geyser (distilled at Bowmor...
806     Bowmore  ...  Bowmore Tempest (Second Release), 10 year old,...
807     Bowmore  ...  Exclusive Malts (distilled at Bowmore) 2001, 5...
935     Bowmore  ...                  Double Barrel Ledaig/Bowmore, 46%
1014    Bowmore  ...          Bowmore, 1991 Vintage, 16 year old, 53.1%
1015    Bowmore  ...  Signatory (distilled at Bowmore), 16 year old,...
1016    Bowmore  ...                Bowmore Devil’s Cask Batch 2, 56.3%
1017    Bowmore  ...                Bowmore Mizunara Cask Finish, 53.9%
1225    Bowmore  ...                Bowmore Tempest IV/Dorus Mor, 55.1%
1226    Bowmore  ...               Bowmore 23 year old Port Wood, 50.8%
1227    Bowmore  ...  Bowmore Vintage Fèis Ìle 2016 Edition 25 year ...
1445    Bowmore  ...          Bowmore, 37 year old, 1968 vintage, 43.4%
1446    Bowmore  ...            Bowmore Bourbon Cask, 1964 Vintage, 43%
1447    Bowmore  ...  Duncan Taylor (distilled at Bowmore), 21 year ...
1448    Bowmore  ...  Whisky Galore (distilled at Bowmore), 16 year ...
1449    Bowmore  ...  Bw3 Elements of Islay (distilled at Bowmore), ...
1450    Bowmore  ...               Bowmore 1999 PX Hand-bottled,  56.1%
1451    Bowmore  ...                            Bowmore 9 year old, 40%
1642    Bowmore  ...  Hart Brothers (distilled at Bowmore) 11 year o...
1643    Bowmore  ...               Bowmore The Devil’s Casks III, 56.7%
1644    Bowmore  ...                       Bowmore Fèis Ìle 2016, 54.9%
1802    Bowmore  ...  Bowmore 'Wine Cask Matured', 1992 vintage, 16 ...
1803    Bowmore  ...  Signatory (distilled at Bowmore), 11 year old,...
1901    Bowmore  ...  Douglas Laing Old Particular (distilled at Bow...
1934    Bowmore  ...  Cadenhead’s (distilled at Bowmore) 11 year old...
2025    Bowmore  ...  Peerless (distilled at Bowmore) 1966, 36 year ...
2026    Bowmore  ...  Douglas Laing Old Particular (distilled at Bow...
2077    Bowmore  ...  The Exclusive Malts (distilled at Bowmore) 15 ...
2099    Bowmore  ...       Bowmore Tempest Batch 3 (10 year old), 55.6%
2100    Bowmore  ...  Elements of Islay Bw1 (distilled at Bowmore), ...
2139    Bowmore  ...  Wemyss Malts (distilled at Bowmore) 1982 Lochi...
2200    Bowmore  ...          Bowmore, 16 year old, 1990 vintage, 53.8%

[59 rows x 7 columns]

In [ ]:
# Bowmore has a 1964 and an NAN - let's see if we can get these
# Bowmore Claret (56%) - replace with 56%
whisky2200['%alc'].iloc[[610]] = '56.0%'

# Bowmore Oloroso Sherry Cask, 1964 Vintage
# google says 42.9%
# https://www.thewhiskyexchange.com/p/925/bowmore-1964-oloroso-sherry-cask
whisky2200['%alc'].iloc[[189]] = '56.0%'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [ ]:
# look for additional issues with % alcohol -- BenNevis
# print('BenNevis:',whisky2200.index[whisky2200["Distillery"] == "BenNevis"].tolist())
whisky2200.iloc[[748, 796, 947, 1001, 1002, 1003, 1216, 1405, 1438, 1929, 2001]]

     Distillery  ...                                               name
748    BenNevis  ...  The Maltman (distilled at Ben Nevis) 17 year o...
796    BenNevis  ...      Ben Nevis 15 year old 1998 (Cask #590), 57.3%
947    BenNevis  ...  The Exclusive Malts (distilled at Ben Nevis) 1...
1001   BenNevis  ...  Signatory (distilled at Ben Nevis), Cask #7438...
1002   BenNevis  ...  Wild Scotsman (distilled at Ben Nevis), 13 yea...
1003   BenNevis  ...        Carn Mor (distilled at Ben Nevis) 1997, 46%
1216   BenNevis  ...                        Ben Nevis, 10 year old, 46%
1405   BenNevis  ...  The Cooper’s Choice (distilled at Ben Nevis) 1...
1438   BenNevis  ...                         Traditional Ben Nevis, 46%
1929   BenNevis  ...       Ben Nevis 1998, Duncan Taylor NC2 range, 46%
2001   BenNevis  ...  Douglas Laing Provenance 8 year old (distilled...

[11 rows x 7 columns]

In [ ]:
# Wild Scotsman (distilled at Ben Nevis), 13 year old, 1992 vintage, cask #693
# google says 46%
# https://scotchhobbyist.com/tag/ben-nevis/
whisky2200['%alc'].iloc[[1002]] = '46.0%'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [ ]:
# where are the other NANs? Can we replace?
# print('N/As in %alc:',whisky2200.index[whisky2200["%alc"] == ""].tolist())
whisky2200.iloc[[619, 906, 980, 1012, 1102, 1247]]

                                    Distillery  ...                                               name
619                               Bunnahabhain  ...                  Bunnahabhain, 12 year old, 46.3%,
906                                    Tomatin  ...             Tomatin, 1982 Vintage (Cask #92), 57%,
980   Johnnie Walker Blenders’ Batch Wine Cask  ...     Johnnie Walker Blenders’ Batch Wine Cask, 40%,
1012                                  Bladnoch  ...  John MacDougall's Selection (distilled at Blad...
1102                         Pentland Skerries  ...                            Pentland Skerries, 46%,
1247                                  Edradour  ...                        Edradour Ballechin #5, 46%,

[6 rows x 7 columns]

In [ ]:
# we can see all of these %s in the name
whisky2200['%alc'].iloc[[619]] = '46.3%'
whisky2200['%alc'].iloc[[906]] = '57.0%'
whisky2200['%alc'].iloc[[980]] = '40.0%'
whisky2200['%alc'].iloc[[1012]] = '55.8%'
whisky2200['%alc'].iloc[[1102]] = '46.0%'
whisky2200['%alc'].iloc[[1247]] = '46.0%'

/usr/local/lib/python3.7/dist-packages/pandas/core/indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

In [ ]:
# clean up the %alc column some more
whisky2200['%alc'] = whisky2200['%alc'].str.replace("%","")
whisky2200['%alc'] = whisky2200['%alc'].str.replace("ABV","")
whisky2200['%alc'] = whisky2200['%alc'].str.strip()

In [ ]:
# preview to make sure this worked
whisky2200.head()

                  Distillery  ...                                             name
0  Johnnie Walker Blue Label  ...                   Johnnie Walker Blue Label, 40%
1                    Bowmore  ...  Black Bowmore, 1964 vintage, 42 year old, 40.5%
2                    Bowmore  ...      Bowmore 46 year old (distilled 1964), 42.9%
3    Compass Box The General  ...                   Compass Box The General, 53.4%
4         Chivas Regal Ultis  ...                          Chivas Regal Ultis, 40%

[5 rows x 7 columns]

In [ ]:
whisky2200.dtypes

Distillery       object
%alc             object
category         object
review.point      int64
price           float64
description      object
name             object
dtype: object

In [ ]:
# try to remove all non-numeric characters
# https://stackoverflow.com/questions/44117326/how-can-i-remove-all-non-numeric-characters-from-all-the-values-in-a-particular#:~:text=To%20remove%20all%20non-digit%20characters%20from%20strings%20in,digits%20%28like%20%DB%B1%DB%B2%DB%B3%DB%B4%DB%B5%DB%B6%DB%B7%DB%B8%DB%B9%2C%20see%20proof%29%20you%20should%20consider
whisky2200['%alc'] = whisky2200['%alc'].str.extract('(\d+)', expand=False)

In [ ]:
# convert to float  
whisky2200['%alc'] = whisky2200['%alc'].astype(float)

In [ ]:
# preview
whisky2200.head()

                  Distillery  ...                                             name
0  Johnnie Walker Blue Label  ...                   Johnnie Walker Blue Label, 40%
1                    Bowmore  ...  Black Bowmore, 1964 vintage, 42 year old, 40.5%
2                    Bowmore  ...      Bowmore 46 year old (distilled 1964), 42.9%
3    Compass Box The General  ...                   Compass Box The General, 53.4%
4         Chivas Regal Ultis  ...                          Chivas Regal Ultis, 40%

[5 rows x 7 columns]

**Merge the datasets**

In [ ]:
# join the dataframes
# whisky86 and whisky2200 will be joined on the "Distillery" column
# whisky_final to be used for NLP? 
whisky_final = whisky86.join(whisky2200.set_index('Distillery'), on="Distillery")

In [ ]:
# preview
whisky_final.head()

   DistCode  ...                                               name
0         0  ...           Aberfeldy 14 year old Single Cask, 58.1%
1         0  ...  Aberfeldy Single Cask (Cask No. 5) 16 year old...
2         0  ...                        Aberfeldy, 21 year old, 40%
3         0  ...  Cask & Thistle (distilled at Aberfeldy), 29 ye...
4         0  ...  That Boutique-y Whisky Company (distilled at A...

[5 rows x 23 columns]

In [ ]:
# reset index
whisky_final = whisky_final.reset_index()

In [ ]:
# rename index column to DistCode
whisky_final = whisky_final.rename(columns={"index":"DistCode"})

In [ ]:
# shape 
whisky_final.shape

(1513, 23)

In [ ]:
# check to make sure that the correct count of all distillerys from Whisky 86 are present in the dataset
whisky_final.Distillery.nunique()

86

In [ ]:
# change name of review.point  - this will cause errors when calling later
whisky_final = whisky_final.rename(columns={"review.point":"review_point"})

In [ ]:
# want to make sure that we've got correct spelling among the Distillery column as well
# 'Belvenie' to 'Balvenie'
# 'Craigallechie' to 'Craigellachie'
# 'Craigganmore' to 'Cragganmore'
# 'Knochando' to 'Knockando'
# 'Laphroig' to 'Laphroaig'
whisky_final['Distillery'] = whisky_final['Distillery'].replace(['Belvenie', 'Craigallechie', 'Craigganmore', 'Knochando', 'Laphroig'],['Balvenie', 'Craigellachie', 'Cragganmore', 'Knockando', 'Laphroaig'])

In [ ]:
# check for NA values in whisky_final
# whisky_final.isnull().values.any()
whisky_final.isnull().sum().sum()

7

In [ ]:
# Where are the N/As?
# listofnull = whisky_final[whisky_final['%alc'].isnull()].index.tolist()
#len(listofnull)
# print(listofnull)
whisky_final.iloc[[3, 4, 20, 25, 31, 44, 48]]

    DistCode  ...                                               name
3          0  ...  Cask & Thistle (distilled at Aberfeldy), 29 ye...
4          0  ...  That Boutique-y Whisky Company (distilled at A...
20         1  ...                Aberlour A’Bunadh (Batch 61), 60.8%
25         1  ...                          Aberlour 12 year old, 40%
31         2  ...                              anCnoc Flaughter, 46%
44         3  ...            Ardbeg Dark Cove Committee Edition, 55%
48         3  ...             Ardbeg Supernova (2010 Release), 60.1%

[7 rows x 23 columns]

In [ ]:
# subset Aberfeldy to look at the % alc
df_Aberfeldy = whisky_final[whisky_final['Distillery']== 'Aberfeldy']

In [ ]:
# call on new df to see if the % alc mean is calculating correctly, depite seeing NAs
df_Aberfeldy

# math says % alc mean is 46.23076923076923 which is equal to what we're seeing in the summary below
# math says review point mean is 86.69230769230769 which is equal to what we're seeing in summary
# math says price mean is 131 which is equal to what we're seeing in summary

    DistCode  ...                                               name
0          0  ...           Aberfeldy 14 year old Single Cask, 58.1%
1          0  ...  Aberfeldy Single Cask (Cask No. 5) 16 year old...
2          0  ...                        Aberfeldy, 21 year old, 40%
3          0  ...  Cask & Thistle (distilled at Aberfeldy), 29 ye...
4          0  ...  That Boutique-y Whisky Company (distilled at A...
5          0  ...  Gordon & MacPhail Cask Strength 1995 (distille...
6          0  ...                         Aberfeldy 18 year old, 40%
7          0  ...  Wemyss Malts Snuffed Candle (distilled at Aber...
8          0  ...  Wemyss Malts Melon Vine 1994 (distilled at Abe...
9          0  ...  Wemyss Malts Toffee Tuile (distilled at Aberfe...
10         0  ...                         Aberfeldy 16 year old, 40%
11         0  ...  Wemyss Malts Banquet of Fruits 1994 (distilled...
12         0  ...                        Aberfeldy, 12 year old, 40%

[13 rows x 23 columns]

In [ ]:
whisky_final.dtypes

DistCode          int64
Distillery       object
Body              int64
Sweetness         int64
Smoky             int64
Medicinal         int64
Tobacco           int64
Honey             int64
Spicy             int64
Winey             int64
Nutty             int64
Malty             int64
Fruity            int64
Floral            int64
Postcode         object
Latitude          int64
Longitude         int64
%alc            float64
category         object
review_point      int64
price           float64
description      object
name             object
dtype: object

In [ ]:
# whisky_collapsed to be used for linear regression and clustering? took the averages of each distillery
whisky_collapsed = whisky_final.groupby('Distillery').mean()

In [ ]:
# reset the index
whisky_collapsed = whisky_collapsed.reset_index()

In [ ]:
# preview to make sure this worked
whisky_collapsed

      Distillery  DistCode  Body  ...       %alc  review_point        price
0      Aberfeldy       0.0   2.0  ...  46.230769     86.692308   131.000000
1       Aberlour       1.0   3.0  ...  49.333333     87.666667    80.600000
2         AnCnoc       2.0   1.0  ...  45.000000     89.000000   178.800000
3         Ardbeg       3.0   4.0  ...  50.344828     89.833333  1464.200000
4        Ardmore       4.0   2.0  ...  50.000000     86.571429   156.428571
..           ...       ...   ...  ...        ...           ...          ...
81     Tobermory      81.0   1.0  ...  49.625000     85.625000   102.250000
82       Tomatin      82.0   2.0  ...  47.363636     85.454545   320.909091
83     Tomintoul      83.0   0.0  ...  43.692308     87.615385   222.923077
84       Tormore      84.0   2.0  ...  49.625000     84.125000   117.125000
85  Tullibardine      85.0   2.0  ...  45.000000     84.470588  1571.176471

[86 rows x 19 columns]

In [ ]:
# take a look at summary statistics
whisky_collapsed.describe()

        DistCode       Body  Sweetness  ...       %alc  review_point        price
count  86.000000  86.000000  86.000000  ...  86.000000     86.000000    86.000000
mean   42.500000   2.069767   2.290698  ...  47.739187     85.931555   375.808828
std    24.969982   0.930410   0.717287  ...   2.691219      2.163957   597.250648
min     0.000000   0.000000   1.000000  ...  42.000000     75.500000    55.250000
25%    21.250000   2.000000   2.000000  ...  46.000000     84.789583   125.000000
50%    42.500000   2.000000   2.000000  ...  47.728421     86.272487   189.905775
75%    63.750000   2.000000   3.000000  ...  49.675481     87.408266   279.787500
max    85.000000   4.000000   4.000000  ...  53.285714     89.833333  3571.953488

[8 rows x 18 columns]

In [ ]:
# make sure the % alc column doesnt have any values that exceed 100%
# print('locations where % alc are > 100%:',whisky_collapsed.index[whisky_collapsed["%alc"] > 100].tolist())
# make sure the % alc column doesnt have any values that exceed 50%
# print('locations where % alc are > 60%:',whisky_collapsed.index[whisky_collapsed["%alc"] > 60].tolist())

locations where % alc are > 100%: []
locations where % alc are > 60%: []

In [ ]:
# write these to csv
# whisky_final.to_csv("projectwhisky_qual_clean.csv")
# whisky_collapsed.to_csv("projectwhisky_quant_clean.csv")

In [ ]:
# Google link to kaggle scotch taste ratings dataset (whisky86): https://drive.google.com/file/d/18rapMF7yRR026TAD0mbtKEdK9epPjh8R/view?usp=sharing
# Google link to kaggle scotch review dataset (whisky2200): https://drive.google.com/file/d/1VYra2R0ewZKBXCkxNAK60YNjNJ7Lxj2y/view?usp=sharing
# Google link to projectwhisky_qual_clean.csv: https://drive.google.com/file/d/14kLPB3YdDpDtYHbc4nFFULnvdpLumbYL/view?usp=sharing
# Google link to projectwhisky_quant_clean.csv: https://drive.google.com/file/d/1NOiR3aY8VU5N7RkZrn6aXLcdYTAyF8vy/view?usp=sharing